version: '3.8'

services:
    # PHP-FPM сервис
    clicks-service:
        build:
            context: .
            dockerfile: Dockerfile
            target: runner
        container_name: clicks-service
        volumes:
            - .:/var/www/html
        depends_on:
            - clickhouse-server
            - rabbitmq

    # Веб-сервер Nginx
    nginx:
        image: nginx:alpine
        container_name: clicks-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    # RabbitMQ брокер сообщений
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: clicks-rabbitmq
        ports:
            - "5672:5672" # Порт для подключения клиентов
            - "15672:15672" # Веб-интерфейс для управления
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq/

    # ClickHouse
    clickhouse-server:
        image: clickhouse/clickhouse-server:latest
        container_name: clicks-service-clickhouse
        ports:
            - "8123:8123"
            - "9000:9000"
        volumes:
            - clickhouse_data:/var/lib/clickhouse/
            - ./docker/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql

    # Laravel Queue Worker
    worker:
        build:
            context: .
            dockerfile: Dockerfile
            container_name: clicks-service-worker
        command: php artisan queue:work rabbitmq --sleep=3 --tries=3
        volumes:
            - .:/var/www/html
        depends_on:
            - rabbitmq
            - clicks-service

    volumes:
    clickhouse_data:
    rabbitmq_data:
